<a href="https://colab.research.google.com/github/RodrigoAnt93/Aulas-Senac/blob/main/Aula_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaListaB = [0, 1, 2, 3, 4, 5, 6, 7]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
meuArray = np.array(minhaLista)
meuArray = np.array(minhaListaB)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
print(meuArray)

[0 1 2 3 4 5 6 7]


In [9]:
minhaLista = list(range(9))

In [10]:
array1 = np.array(range(9))

In [12]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [15]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [17]:
array3 = np.arange(0, 10, 0.5, dtype = int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
array4 = np.arange(12)

In [20]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [21]:
type(array4)

numpy.ndarray

In [22]:
array4.dtype

dtype('float64')

In [32]:
vetor1 = np.array([1, 2, 3, 4])
print(vetor1)

[1 2 3 4]


In [33]:
vetor1[3]

4

In [28]:
vetor1[0:2]

array([0, 1])

In [29]:
print(vetor1[0:2])

[0 1]


In [36]:
s = np.array(['python', 'profissional', 'java', 'água'])
s

array(['python', 'profissional', 'java', 'água'], dtype='<U12')

In [38]:
s = np.array(['python', 'profissional',123524555652, 'java', 'água'])
s

array(['python', 'profissional', '123524555652', 'java', 'água'],
      dtype='<U21')

In [39]:
vetor1[2] = 10

In [40]:
vetor1[0] = 'novo elemento'

ValueError: ignored

In [41]:
vetor1[0] = 45.6
vetor1

array([45,  2, 10,  4])